### ISSUE TITLE
Resume Usage

### ISSUE THREAD

**Issue by quentinlesceller** [gcarq/rusty-blockparser#10]
I'm having trouble with the `--resume` flag.
I have run csv dump once like that:
` rusty-blockparser -d /data/.bitcore/data/blocks --chain-storage chain.json -t 3 csvdump .`
Once finished I did:
` rusty-blockparser --resume -d /data/.bitcore/data/blocks --chain-storage chain.json -t 3 csvdump .`

However, it seems the program start over the indexing process.

Thank you for your help.

**Comment by quentinlesceller** [comment]
Nevermind no problem after all. New indexing from scratch seems mandatory.

**Comment by gcarq** [comment]
Yes, this is currently mandatory because it doesn't keep track of the position from the latest processed block.
