### ISSUE TITLE
Balances command Killed

### ISSUE THREAD

**Issue by Aness-s** [gcarq/rusty-blockparser#103]
I tried running both rusty-blockparser unspentcsv and rusty-blockparser balances and it runs for about 10 minutes then at the 31 000 block mark it terminates without any error message. I know my chain is intact as I ran a bitcoin sync this morning and have the up to date chain. I was also able to run the csvdump command with no issue, only having problems with the balances and unspentcsv ones. I was sure to use the command correctly and provided a destination path as well. 

Here is the command line before it terminates
 INFO - parser: Status:  318137 Blocks processed. (remaining:  490460, speed:    61 blocks/s)
 INFO - parser: Status:  318753 Blocks processed. (remaining:  489844, speed:    61 blocks/s)
Killed

**Comment by gcarq** [comment]
Can you check the system logs and memory pressure when it gets killed? Seems like you ran out of memory and the process got killed by the OOM Killer. That would explain why `csvdump` had no issue (because it doesn't need to hold anything in memory), but `balances` and `unspentcsv` got killed, because they have to keep all UTXOs in memory until it finds the matching UTXO that spents the old one.

**Comment by Aness-s** [comment]
Your right, I checked the system logs and I saw an out of memory oom kill message. Any way I could solve/get around this?

**Comment by gcarq** [comment]
On linux you can work around this by creating a large enough swap (32GiB). I'm not sure if there is an equivalent on windows however.

**Comment by Aness-s** [comment]
Makes sense, ill try that out. Is a 32gb swap file really necessary? I started it with a 4gb swap file, should I terminate it and create a larger one or should I be fine with my existing one

**Comment by gcarq** [comment]
Yes I think 32GiB are necessary, from the README:
```
The required memory usage depends on the used callback:

    simplestats: ~100MB
    csvdump: ~100M
    unspentcsvdump: ~18GB
    balances: ~18GB

NOTE: Those values are taken from parsing to block height 639631 (17.07.2020).
```

**Comment by Aness-s** [comment]
Thanks for the help with this. One thing I Noticed is that around the half way mark the balance and unspentcsv commands start to preform really slow, it goes down to 2-3 blocks per second and then eventually less than 1 block per second. Is this due to me having a swap file for memory or is this just the normal run duration?

**Comment by gcarq** [comment]
Yes this is due to the swap file unfortunately

**Comment by Aness-s** [comment]
Thanks for your help
