### ISSUE TITLE
Resume without indexing

### ISSUE THREAD

**Issue by quentinlesceller** [gcarq/rusty-blockparser#11]
Just wondering if there is a way to resume without indexing or any idea for optimizing the indexing ?
Great tool BTW !

**Comment by kavinaravind** [comment]
Hey! Your tool is great, and its been very useful to me. I was also wondering the same thing as quentinlesceller. Hoping that there would be some way to optimize/remove indexing!

**Comment by gcarq** [comment]
I think it would be possible to resume without re-indexing with some small code changes. This check is there as a kind of sanity mechanism under the assumption that a bitcoin client could rearrange the blockchain (*.blk files) on the filesystem.

**Comment by mikispag** [comment]
Putting a "resume without reindexing" as an option would be awesome!

**Comment by gcarq** [comment]
With the latest release [0.7.0](https://github.com/gcarq/rusty-blockparser/releases/tag/0.7.0) the Bitcoin Core indexing is reused which fixes this. No more indexing
