### ISSUE TITLE
Import to Neo4j

### ISSUE THREAD

**Issue by ghost** [gcarq/rusty-blockparser#14]
Is there a way to import the csv files into a neo4j database?

**Comment by gcarq** [comment]
Never used neo4j before, but there is an official guide how to import data from csv: https://neo4j.com/developer/guide-import-csv/

As far as I can see this should work out of the box for `csvdump`

**Comment by landoephan** [comment]
thanks a lot! So I dont have to do any changes on the data structure?

**Comment by gcarq** [comment]
I think not, but please let me know if you run into an issue.

**Comment by landoephan** [comment]
I tried to import the data. Loading the 4 CSV files into Neo4j took 1,3 TB data and when I tried to build the relationships between the data it crashes. So unfortunatly it doesnt seem to be working.

**Comment by Goro2030** [comment]
Is there a specific reason why you would like to use Neo4j? Normally, people import the blockchain into MySQL to run queries, or do whatever you need to do (i.e. a blockexplorer )

I'd close this issue, it's too old, and is just a question, not an issue.
