### ISSUE TITLE
Speed decreasing to 0

### ISSUE THREAD

**Issue by dark0venom** [gcarq/rusty-blockparser#17]
Speed is decreasing from X to 0 and the process get killed at the second phase. How can I increase the debug level to 2. I can't put a option on flag -v ?

**Comment by gcarq** [comment]
Possible related to https://github.com/gcarq/rusty-blockparser/issues/13.

You can increase the debug level with multiple -v flags. e.g.: `-vv` or `-v -v`

**Comment by gcarq** [comment]
Is this issue still relevant?

**Comment by v1nsai** [comment]
Experiencing this also.  Number of blocks/second always goes down until getting close to 0 then seems to crash.  All output files are named like `file.csv.tmp`

**Comment by v1nsai** [comment]
I've tried using @mikispag emergency fix in issue #13 but after running for about an hour the speed is under 200 blocks/sec and steadily decreasing, doesn't seem to have fixed it.

**Comment by gcarq** [comment]
Please retry with the latest release [0.7.0](https://github.com/gcarq/rusty-blockparser/releases/tag/0.7.0). Feel free to reopen if this is still an issue.
