### ISSUE TITLE
what is a transaction lockTime

### ISSUE THREAD

**Issue by int8** [gcarq/rusty-blockparser#19]
Hi there, 

first of all, good work, this is what I have been after for some time, 

I wonder what is a lockTime for given transaction

**Comment by int8** [comment]
I can already answer myself:

https://www.cryptocompare.com/coins/guides/what-is-bitcoin-transaction-locktime/

**Comment by gcarq** [comment]
Glad you like it. Thanks for posting the answer. Feel free to open another issue if you have further questions
