### ISSUE TITLE
Wrong indexOut in tx_out.csv?

### ISSUE THREAD

**Issue by guifereis** [gcarq/rusty-blockparser#2]
Hi,

I believe there is a bug with the indexOut field in tx_out.csv.

Running: "./rusty-blockparser -t 4 csvdump csvdump/"

The indexOut listed in the .csv does not match up with the actual output index.

Multiple rows with the same txid have the same indexOut too, e.g. row#172 with txId f4184fc596403b9d638783cf57adfe4c75c605f6356fbc91338530e9831e9e16 has two outputs, both with indexOutput 1.

Some rows have an indexOut bigger than the number of outputs in the transaction. For example, on line #38948 in tx_out.csv:

7db18e491ffd40e2af82be0ea938c9c79e5cb9751f951b0c0fff29b9f4d1a000;7;5000000000;76a91461b66ebb35bf3bf51ed2daf510e4835a2844f89d88ac;19uf6F6EDijkH4ZUaqsi3pZ2SVD6A5RG8X

[Looking this transaction up elsewhere](https://blockchain.info/tx/7db18e491ffd40e2af82be0ea938c9c79e5cb9751f951b0c0fff29b9f4d1a000) shows it only has 1 input - not 7, so an output couldn't have an index of 7.

Am I misunderstanding what indexOut means, or is this actually a bug? I tried to find it but couldn't - not very familiar with Rust :)

Thanks in advance.

**Comment by guifereis** [comment]
EDIT: I believe the bug is in csvdump.rs, around line 100. Notice how right before `for output in &tx.value.outputs` there is `let i = i as u32;`. And this variable i is passed into `output.as_csv(&txid_str, i)`, but it doesn't keep track of the index of the tx output - rather, it's the result of `for (i, tx) in block.txs.iter().enumerate() {`

**Comment by gcarq** [comment]
You are right, I mixed the index up somehow. Thanks for investigating, I will fix this as soon as I'm at home.

**Comment by gcarq** [comment]
PR https://github.com/gcarq/rusty-blockparser/pull/3 should fix your issue, could you run a quick test?

**Comment by guifereis** [comment]
I can't test it until later, but I just gave the PR a quick look and I don't see where/how txout_idx is incremented.

**Comment by gcarq** [comment]
Oh damn. I shouldnt write code in a hurry ;-). I will change it later and come back to you.

**Comment by gcarq** [comment]
fixed with 0.5.0

**Comment by guifereis** [comment]
Except it won't compile - see my comment on the commit :) and thanks!

**Comment by gcarq** [comment]
Did you pull the new changes? `as_csv()` expects an usize for the index: https://github.com/gcarq/rusty-blockparser/commit/0b102ed1635100cff1c97d7e2542e47d3a6269bf#diff-ecb7fa6af59617b0414f2244c129d48aR171

It's also a good idea to issue a `cargo update` because I've updated some dependencies

**Comment by gcarq** [comment]
Is this issue still relevant?
