### ISSUE TITLE
Possible to resume csvdump?

### ISSUE THREAD

**Issue by v1nsai** [gcarq/rusty-blockparser#21]
Like several others I've been experiencing a gradual drop in performance eventually followed by a crash.  This wouldn't be so bad if we could resume csvdump where it left off instead of having to restart every time.  Has anyone figured out a way to do this?  

I don't speak Rust at all and don't have the time to try to figure this out now, but if I do have some time to figure it out I'll share here

**Comment by skywinder** [comment]
It looks like a very useful, but unavailable feature for now.

p.s. a duplicate of #10

**Comment by skywinder** [comment]
and related to #11

**Comment by gcarq** [comment]
Version [0.7.0](https://github.com/gcarq/rusty-blockparser/releases/tag/0.7.0) should have better performance in general. Now you can also specify `--start` and `--end` which takes a block height, so you could create a csvdump in 50k block steps. I'm closing this, feel free to reopen.
