### ISSUE TITLE
No blk files found

### ISSUE THREAD

**Issue by jRazer** [gcarq/rusty-blockparser#26]
Parser not found blockchain files

`root@ubuntu-minimal:~/rusty-blockparser/target/release# ./rusty-blockparser -vv -c litecoin --chain-storage litecoin --blockchain-dir ~/.litecoin/blocks/ csvdump lite`
`[19:39:16] INFO - main: Starting rusty-blockparser v0.6.1 ...`
`[19:39:16] DEBUG - main: Using LogLevel TRACE`
`[19:39:16] INFO - blkfile: Reading files from /root/.litecoin/blocks/ ...`
`[19:39:16] TRACE - blkfile: Found 0 blk files`
`[19:39:16] ERROR - rusty_blockparser: Cannot load blockchain from: '/root/.litecoin/blocks/'. No blk files found! Runtime Error`

**Comment by mikispag** [comment]
This is probably due to https://github.com/gcarq/rusty-blockparser/pull/25/ - @RCasatta, can you check? Thanks!

**Comment by mikispag** [comment]
I can reproduce with regular, non symlink files.

**Comment by RCasatta** [comment]
Sorry, I can't reproduce on Mac OS X 10.12.6 and Ubuntu 16.04.3 LTS
rustc 1.21.0
rusty-blockparser 0.6.1

Is yours a scan from scratch or perhaps you have [min_blk_idx](https://github.com/gcarq/rusty-blockparser/blob/master/src/blockchain/utils/blkfile.rs#L62) already at the last block file?

**Comment by mikispag** [comment]
I have this problem when running from scratch too.

**Comment by gcarq** [comment]
Does it make a difference when `--blockchain-dir` is specified?

**Comment by mikispag** [comment]
I can't verify right now, but what do you have in mind? :)

**Comment by gcarq** [comment]
Nothing particular, but I tested it with Dogecoin and setting a blockchain directory, which worked as expected

**Comment by jRazer** [comment]
With --blockchain-dir for litecoin and without - for bitcoim 
same error

**Comment by mikispag** [comment]
If --reindex is passed, it works to me.

**Comment by mikispag** [comment]
This is due to start_blk_idx being set to a negative number in my fork. Will fix on my side. Unsure if the problem is also here.

**Comment by jRazer** [comment]
Thanks, wait for fixed version
