### ISSUE TITLE
How large are the CSV dumps?

### ISSUE THREAD

**Issue by plingampally** [gcarq/rusty-blockparser#29]
The bitcoin blockchain is about 145GB. I was just wondering how much space I need to have in addition to that.

**Comment by gcarq** [comment]
I'm assuming you're talking about `csvdump` and not `unspentcsvdump`. It would probably take twice or more space (just a wild guess) because a csv dump is in ASCII and the blockchain itself is stored as binary

**Comment by rawmaterials** [comment]
as of 2-3 jan 2018, till blocks 502388.

blocks-0-502388 = 117 MB
transactions-0-502388.csv = 37 GB
tx_out-0-502388.csv = 117 GB
tx_in-0-502388.csv = 236 GB

**Comment by DavidNagilla** [comment]
490 GB as of Oct 2018

**Comment by gcarq** [comment]
csvdump until block 639273 is about 730 GiB. unspentcsvdump should be about 8-9GiB.

**Comment by Goro2030** [comment]
Adding to the documentation, but will need to be updated regularly to keep up with the blockchain growing. I recommend we close this Issue @gcarq

**Comment by gcarq** [comment]
Agree, this should be added to the documentation. Closing this
