### ISSUE TITLE
Perform CSV dump after certain blockheight? 

### ISSUE THREAD

**Issue by plingampally** [gcarq/rusty-blockparser#30]
I'm only interested in the last 1 years worth of blocks, is there a way I can specify the block height? It seems that for a lot of people the parser is crashing when working with the entire blockchain.

**Comment by gcarq** [comment]
It's not implemented right now, but it would be relative easy to implement it directly in a callback:
```
e.g.:
if height < X:
    continue
```

I'm happy to accept a PR for this

**Comment by gcarq** [comment]
This has been implemented with [0.7.0](https://github.com/gcarq/rusty-blockparser/releases/tag/0.7.0). See `--start` and `--end` parameter to specify a custom range. Feel free to reopen if this is still an issue
