### ISSUE TITLE
Possible to extract address balance data ?

### ISSUE THREAD

**Issue by OPrtr** [gcarq/rusty-blockparser#32]
Hi,

Is it possible to parse for address balance or should one have to calculate balances after the parse ?

Thanks

**Comment by TheWizIL** [comment]
That will be great to get all address balance (and ignore empty address)

**Comment by rawmaterials** [comment]
+1

**Comment by Goro2030** [comment]
+1

**Comment by gcarq** [comment]
This has been implemented as `unspentcsvdump`.
Just did a test on the latest master branch. The resulting csv file is 8-9GiB in size for data up to block ~630000 (current height)
Example: 

```
./rusty-blockparser -d /path/to/bitcoin/blocks unspentcsvdump /path/to/dump
```
