### ISSUE TITLE
ERROR - dispatch: Genesis hash for `Bitcoin` does not match:

### ISSUE THREAD

**Issue by petermack** [gcarq/rusty-blockparser#39]
Hi, I'm getting this error after processing is done:
> [08:04:07] ERROR - dispatch: Genesis hash for `Bitcoin` does not match:
>   Got: 00000000000091108032fce57099b7dad0cc42444e400f540db05c18a88d10b2
>   Exp: 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f Validation Error

If I run:
> ./rusty-blockparser -n -d /mnt/c/Users/peter/AppData/Roaming/Bitcoin/blocks unspentcsvdump /home/peter/data 

I get:
> [08:03:38] INFO - dispatch: Status: 381134 Blocks added to index. (avg:   328 blocks/sec)
> [08:03:49] INFO - dispatch: Status: 382405 Blocks added to index. (avg:   326 blocks/sec)
> [08:04:00] INFO - dispatch: Status: 383670 Blocks added to index. (avg:   324 blocks/sec)
> [08:04:05] INFO - dispatch: All threads finished.
> [08:04:05] INFO - dispatch: Done. Processed 384321 blocks in 19.79 minutes. (avg:   323 blocks/sec)
> [08:04:05] INFO - dispatch: Saving block headers as chain.json ...
> [08:04:07] ERROR - dispatch: Genesis hash for `Bitcoin` does not match:
>   Got: 00000000000091108032fce57099b7dad0cc42444e400f540db05c18a88d10b2
>   Exp: 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f Validation Error

My data directory looks like this with empty files:
 
> peter@peter-THINK:~/data$ ls -la
> total 0
> drwxrwxrwx 0 peter peter 512 Jan  7 17:59 .
> drwxr-xr-x 0 peter peter 512 Jan  7 18:41 ..
> -rw-rw-rw- 1 peter peter   0 Jan  7 17:59 blocks.csv.tmp
> -rw-rw-rw- 1 peter peter   0 Jan  7 17:59 transactions.csv.tmp
> -rw-rw-rw- 1 peter peter   0 Jan  7 17:59 tx_in.csv.tmp
> -rw-rw-rw- 1 peter peter   0 Jan  7 17:59 tx_out.csv.tmp
> -rw-rw-rw- 1 peter peter   0 Jan 15 07:44 unspent.csv.tmp

Any ideas? I just downloaded a fresh copy of bitcoin core over the weekend, and re-downloaded the entire blockchain. Thanks!

**Comment by SaxoBeatMos** [comment]
так что никто не знает причину?

**Comment by cboseak** [comment]
I had a similar issue.... Its either not seeing or you don't have the whole block chain. take the got value from above and search blockchain.info.... it looks like its looking a block from 2011 first and throwing an exception because it's expecting the first block. 

Find a torrent of the whole blockchain and download through there. Don't use the one that bitcoin-core downloads

**Comment by salber** [comment]
is the bitcoin-core download that buggy?

I keep getting false orphaned blocks.

**Comment by Giszmo** [comment]
This happened to me, too now.

```
[05:11:25] INFO - dispatch: All threads finished.
[05:11:25] INFO - dispatch: Done. Processed 448248 blocks in 7.89 minutes. (avg:   947 blocks/sec)
[05:11:25] INFO - dispatch: Saving block headers as chain.json ...
[05:11:25] ERROR - dispatch: Genesis hash for `Bitcoin` does not match:
  Got: 0000000000009afd5daa29bcbbd4dc49bfbaad1a00f58ec5fb9a92574994a968
  Exp: 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f Validation Error
```

I think it might be due to bitcoind running a reindex or something?

**Comment by Giszmo** [comment]
So ... in case these details matter: I run the parser in a docker container that I only expose the ~/.bitcoin folder to and the blockchain files are on a different files, too, I added that separately.

```
docker run -it \
  --volume ~/.bitcoin:/root/.bitcoin \
  --volume /media/some/mount/blockchain:/root/.bitcoin/blocks \
  --volume /media/some/other/folder:/dump \
  ubuntu:18.04 bash
...
root@64d54b76bad0:/rusty-blockparser# history
    2  apt update
    3  apt full-upgrade -y
    4  apt install -y git cargo
    5  git clone https://github.com/gcarq/rusty-blockparser.git
    6  cd rusty-blockparser
    7  cargo build --release
    8  cargo test --release
    9  ./target/release/rusty-blockparser -t 3 csvdump /dump/
```

and this now runs to said block only. I see nothing special around that block though:

```
$ bitcoin-cli getblock 0000000000009afd5daa29bcbbd4dc49bfbaad1a00f58ec5fb9a92574994a968
{
  "hash": "0000000000009afd5daa29bcbbd4dc49bfbaad1a00f58ec5fb9a92574994a968",
  "confirmations": 448332,
  "strippedsize": 2594,
  "size": 2594,
  "weight": 10376,
  "height": 119992,
  "version": 1,
  "versionHex": "00000001",
  "merkleroot": "6d4da94d700439e0bff75c16d892b8e440a6e3b66e5015f787c4b5db8f6463bc",
  "tx": [
    "91533623542fc1d949b33b510573cc6bd319f8cc7a4a91e1f34e2fe04d63adf7",
    "0acfd7cbed8f7ad95b773454da1704837c6ed0bcf93f9808884257d7764930ca",
    "d71cffa11ad70348631682bcaa6019137091d097b131b842e04f9a9496843983",
    "8ea86f184d9162c8363ff62c8130bf420125b2081f337c56e1c38336de1d8c97",
    "d73325154fe791dde195464e72c90646eaf0477a1b9b9ff5435d7d13e00a458e",
    "96e4ed6ec46a0bcf3852d2f41b611855ea32fafbf1394a2fcc6e1ec53f42ada7",
    "5b79292912fb06717d326ebe01f0c8e6b68b805113d816ddf9d3564318ca3b53",
    "79c3e2638e9c70bd50ec654c246fcb5c2a453703ed8cb24063cc55a387054370"
  ],
  "time": 1303683865,
  "mediantime": 1303682120,
  "nonce": 790673241,
  "bits": "1b00b5ac",
  "difficulty": 92347.59095209427,
  "chainwork": "0000000000000000000000000000000000000000000000003d13d58ef3ae46d4",
  "nTx": 8,
  "previousblockhash": "0000000000001fffd8a47ddd5cb838dadf67429218f5b89bb013f10591dbc0bd",
  "nextblockhash": "0000000000007ba4bde6be436428cd4ec21495012d9d5c4bc0b686a0d7c50870"
}
$ bitcoin-cli getblock 0000000000001fffd8a47ddd5cb838dadf67429218f5b89bb013f10591dbc0bd ; bitcoin-cli getblock 0000000000007ba4bde6be436428cd4ec21495012d9d5c4bc0b686a0d7c50870
{
  "hash": "0000000000001fffd8a47ddd5cb838dadf67429218f5b89bb013f10591dbc0bd",
  "confirmations": 448333,
  "strippedsize": 5687,
  "size": 5687,
  "weight": 22748,
  "height": 119991,
  "version": 1,
  "versionHex": "00000001",
  "merkleroot": "f127325382b2ab52e9b0117e2c33fe5c3a99f6d10c993252f296b3ca32d04233",
  "tx": [
    "33f2ca3b26f5fe3bca6bf22af890e42d581943cdd88a04dcdee545a8807488f5",
    "07163a083248cd2f5c98f6e062f3dce7a8a8b3f77f39d2f99e31cd85074875f5",
    "78be26b94705ca01ca21e16fc60fedc1a5a55c82150867d2a5086c6af078db86",
    "d57332a251cf88e02d367e37c9ab39a2b953e835f5b3647126854dd05eaae326",
    "116e95abf1428e4aa5ded493ff8eb693ce233ec639d1a8a51985bc1cbdbf28c5",
    "d8f648782352d55dfc203ee4d7a7ce686b68ce617dfe4000822f0e42c719237f",
    "d41df3494be082e54ee1a7e7ccae1c148d1da18e9e5db22110da880b4a5808c5",
    "bcef404b987e36bcc3f1792a707075c2f46b39ffa1a96e93dcfa5ff531528598",
    "bf7bb0daa163024ded68f20f9a11ee28788d8b8f8e873102de288299c4a0b88f",
    "4436761da9a96dae337fe134e252b26b862e8ff797c235ff940ea4e6ed68f680",
    "ba4dc72f1c37456f1b46115c820021d694d1bfc6e43396e8be83e6b4b6149140"
  ],
  "time": 1303683745,
  "mediantime": 1303681396,
  "nonce": 2506320763,
  "bits": "1b00b5ac",
  "difficulty": 92347.59095209427,
  "chainwork": "0000000000000000000000000000000000000000000000003d126cd1f3a8a3e0",
  "nTx": 11,
  "previousblockhash": "0000000000000bce63729e4b82cf228e15cb255740dc00d9e2a9c30b518d30df",
  "nextblockhash": "0000000000009afd5daa29bcbbd4dc49bfbaad1a00f58ec5fb9a92574994a968"
}
{
  "hash": "0000000000007ba4bde6be436428cd4ec21495012d9d5c4bc0b686a0d7c50870",
  "confirmations": 448331,
  "strippedsize": 652,
  "size": 652,
  "weight": 2608,
  "height": 119993,
  "version": 1,
  "versionHex": "00000001",
  "merkleroot": "56a46cadaed4d96df21558b5b328ef4b89681f4f3030d7c3a5646482c184a018",
  "tx": [
    "5fa7f5543bbe5d7dd84a641162c58ef335c9809d3a3520be448b77a824355ac0",
    "94f4b3aa3f0637262482c9a1f12b2b6201d190b17f98f2d088eaedf60807f97f"
  ],
  "time": 1303683900,
  "mediantime": 1303682187,
  "nonce": 954538093,
  "bits": "1b00b5ac",
  "difficulty": 92347.59095209427,
  "chainwork": "0000000000000000000000000000000000000000000000003d153e4bf3b3e9c8",
  "nTx": 2,
  "previousblockhash": "0000000000009afd5daa29bcbbd4dc49bfbaad1a00f58ec5fb9a92574994a968",
  "nextblockhash": "0000000000000ca0fe4b84c237b3aef64438ee217efa856112a0fea54d82f665"
}
```

**Comment by Giszmo** [comment]
After a fresh download of the blockchain, I got an earlier crash from #31 and turning that `error!()` into an `info()`, I now get this error again, with a different block:

```
[22:11:34] ERROR - dispatch: Genesis hash for `Bitcoin` does not match:
  Got: 0000000000001cb6dec617ca2cee92009c5b6b40b43e43e0ec9f97aa4b06d8fc
  Exp: 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f Validation Error
```

This is not as much fun as I had hoped for :(

**Comment by gcarq** [comment]
Please retry with the latest release [0.7.0](https://github.com/gcarq/rusty-blockparser/releases/tag/0.7.0). Feel free to reopen if this is still an issue.
