### ISSUE TITLE
Testnet flag did not parse Testnet3 block data

### ISSUE THREAD

**Issue by maven00** [gcarq/rusty-blockparser#4]
I was unable to successfully parse TestNet3 block data using the TestNet3 flag.  

I used the following command to run on TestNet block data:
`./rusty-blockparser -t 1 -c testnet3 --blockchain-dir <dir> csvdump ... <dir> `

With the following error message:

> [19:17:28] INFO - main: Starting rusty-blockparser v0.5.0 ...
> [19:17:28] INFO - blkfile: Reading files from (dir) ...
> [19:17:28] INFO - parser: Parsing TestNet3 blockchain ...
> [19:17:28] INFO - parser: Parsing with mode HeaderOnly (first run).
> [19:17:28] ERROR - worker-0: Got invalid magic value for TestNet3: 0xd9b4bef9, expected: 0x709110b Validation Error
> [19:17:28] ERROR - dispatch: Got invalid magic value for TestNet3: 0xd9b4bef9, expected: 0x709110b Validation Error

I was able to successfully parse the testnet data using the `-c bitcoin` flag.

**Comment by gcarq** [comment]
Are you sure the given blockchain directory contains TestNet3 blocks?
As specified [here](https://en.bitcoin.it/wiki/Protocol_documentation) the magic number for TestNet3 is `0x0709110B` and for the mainnet it is `0xD9B4BEF9`, so it seems you are trying to load a MainNet blockchain.

**Comment by maven00** [comment]
PBCAK...thanks for the help.  This is a great program with well organized code.  Thanks for putting this together.

**Comment by gcarq** [comment]
You're welcome. Thanks for the kind words and don't hassle to ask if something is unclear.
