### ISSUE TITLE
blank address in tx_out.csv when vout type is witness_v0_keyhash

### ISSUE THREAD

**Issue by aichemzee** [gcarq/rusty-blockparser#44]
Blank address are dumped during a csvdump callback when vout type is witness_v0_keyhash.
For example txid : "f1b2caa3153aa0c37dcfcdff69214911512804c55ee162ba85cc65b1597903a2"
Is there an easy fix for this?

**Comment by gcarq** [comment]
No easy fix for now, but I'm working on it

**Comment by gcarq** [comment]
Checkout #62, there should be full SegWit support with this for Bitcoin.
