### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by Napulsnik** [gcarq/rusty-blockparser#47]
Hello. Ubuntu 16, 32gb ram, 500gb ssd, 80gb swap

> [17:36:43] INFO - dispatch: Status: 519565 Blocks processed. (left:   8881, avg:    19 blocks/sec)
> [17:36:53] INFO - dispatch: Status: 519577 Blocks processed. (left:   8869, avg:    19 blocks/sec)
> [17:37:04] INFO - dispatch: Status: 519589 Blocks processed. (left:   8857, avg:    19 blocks/sec)
> [17:37:14] INFO - dispatch: Status: 519602 Blocks processed. (left:   8844, avg:    19 blocks/sec)
> Segmentation fault

Any ideas?

**Comment by rawmaterials** [comment]
+1

**Comment by rawmaterials** [comment]
add these 
-t 1 --backlog 20

so your command becomes

./rusty-blockparser -t 1 --backlog 20 csvdump /path/to/dump/

**Comment by Napulsnik** [comment]
> add these
> -t 1 --backlog 20
> 
> so your command becomes
> 
> ./rusty-blockparser -t 1 --backlog 20 csvdump /path/to/dump/

Thank you. Better try this parser - **https://github.com/mycroft/chainstate**. It works much faster and consumes less resources.

**Comment by gcarq** [comment]
Please retry with the latest release [0.7.0](https://github.com/gcarq/rusty-blockparser/releases/tag/0.7.0), a lot of issues have been fixed.
