### ISSUE TITLE
source compile problem

### ISSUE THREAD

**Issue by hamnaz** [gcarq/rusty-blockparser#51]
$ cargo build
warning: profile `doc` is deprecated and has no effect
   Compiling cfg-if v0.1.6
   Compiling unicode-width v0.1.5
   Compiling rustc-serialize v0.3.24
   Compiling strsim v0.6.0
   Compiling bitflags v0.9.1
   Compiling ansi_term v0.9.0
   Compiling vec_map v0.8.1
   Compiling byteorder v1.1.0
   Compiling seek_bufread v1.2.2
   Compiling log v0.4.6
   Compiling num-traits v0.2.6
   Compiling libc v0.2.47
   Compiling log v0.3.9
   Compiling term_size v0.3.1
   Compiling rand v0.4.5
   Compiling atty v0.2.11
   Compiling time v0.1.42
   Compiling textwrap v0.8.0
   Compiling num-integer v0.1.39
   Compiling num-complex v0.2.1
   Compiling clap v2.26.2
   Compiling rand v0.3.22
   Compiling num-bigint v0.2.2
   Compiling num-iter v0.1.37
   Compiling rust-crypto v0.2.36
   Compiling num-rational v0.2.1
   Compiling num v0.2.0
   Compiling rust-base58 v0.0.4
   Compiling rusty-blockparser v0.6.1 (/home/chawla/rusty-blockparser)
warning: use of deprecated item 'std::env::home_dir': This function's behavior i                                                 s unexpected and probably not what you want. Consider using the home_dir functio                                                 n from https://crates.io/crates/dirs instead.
   --> src/blockchain/utils/mod.rs:131:19
    |
131 |     PathBuf::from(env::home_dir().expect("Unable to get home path from env                                                 !"))
    |                   ^^^^^^^^^^^^^
    |
    = note: #[warn(deprecated)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 40.01s

**Comment by hamnaz** [comment]
hello all 
i successfuly compile last 3 may 2018 sourcecode  for unspent in 1 feb 2019
i will write to developer for write new readme for compile and use in year 2019

**Comment by rawmaterials** [comment]
warning: use of deprecated item 'std::env::home_dir': This function's behavior is unexpected and probably not what you want. Consider using the home_dir function from https://crates.io/crates/dirs instead.
   --> src/blockchain/utils/mod.rs:131:19
    |
131 |     PathBuf::from(env::home_dir().expect("Unable to get home path from env!"))
    |                   ^^^^^^^^^^^^^
    |
    = note: #[warn(deprecated)] on by default

**Comment by gcarq** [comment]
I've fixed this issue with [0.7.0](https://github.com/gcarq/rusty-blockparser/releases/tag/0.7.0), also the `Cargo.lock` file has been committed, which should avoid this problem in the future. Feel free to reopen if this is still an issue.
