### ISSUE TITLE
Size of output csvdump?

### ISSUE THREAD

**Issue by skywinder** [gcarq/rusty-blockparser#55]
It would be nice to specify a rough estimate of the output data. 
I set 400Gb, but it looks like it's not enough. Do you have any estimations?

**Comment by makabress** [comment]
last pars
Dumped all 616392 blocks:
        -> transactions: 500765035
        -> inputs:       1225052754
        -> outputs:      1330630869
blocks csv size         150 Mo
Trasaction csv size      66 Go
TX-in csv size            434 Go
TX-out csv size         208 Go

**Comment by skywinder** [comment]
thanks!

**Comment by skywinder** [comment]
@gcarq It would be nice to add this info to readme. would you like to?
