### ISSUE TITLE
csvdump

### ISSUE THREAD

**Issue by dibabr** [gcarq/rusty-blockparser#67]
Hi.
Run with parametrs: 
rusty-blockparser -s 655239 -e 655240 -d y:\blocks\ csvdump t:\CSV

ruturn files' names  
tx_out-0-1.csv
transactions-0-1.csv
tx_in-0-1.csv
blocks-0-1.csv
can be: 655239-655240 

into file: blocks-0-1.csv
00000000000000000004a1bbdf5771f90c7a3b94b573fbf3993f4eb47d45dfa0;0;536870912;1272426;0000000000000000000d6a44b46922ebf506f4fb1b9d7914ad3d02f9d5e24c62;e50b08133ad1d208043bea23e6313de79c530f21295c6fe1bbda5500745486bc;1604387714;386798414;237847184

where hash 00000000000000000004a1bbdf5771f90c7a3b94b573fbf3993f4eb47d45dfa0 - it block 655191!!!!!
https://www.blockchain.com/ru/btc/block/00000000000000000004a1bbdf5771f90c7a3b94b573fbf3993f4eb47d45dfa0

and into file: blocks-0-1.csv begin block 0!!!!!!!
can be 655239 and 655240

it's case bigin with 461247 block
hash - 0000000000000000003c6fe479122bfa4a9187493937af1734e1e5cd9f198ec7 - !!!!!!!!!!!!

**Comment by jl2035** [comment]
I've also noticed this problem. It seems that -s parameter has no effect.

**Comment by gcarq** [comment]
This has been fixed with 0.9.0
