### ISSUE TITLE
error: could not compile rusty-blockparser

### ISSUE THREAD

**Issue by MarkFromGarden** [gcarq/rusty-blockparser#69]
With Ubuntu 20.10 (64 bit), and rustc 1.49.0 (e1884a8e3 2020-12-29)
the command:
$ cargo build --release

Give me an error:
warning: use of deprecated associated function `std::error::Error::description`: use the Display impl or to_string()
  --> src/blockchain/proto/script.rs:18:30
   |
18 |         write!(f, "{}", self.description())
   |                              ^^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: 1 warning emitted

**Comment by Mammux** [comment]
That's actually a warning, not an error. You can replace .description() with .to_string() and remove Error from the use statement in the beginning of the file (src/blockchain/proto/script.rs).
