### ISSUE TITLE
option needed

### ISSUE THREAD

**Issue by privatenode** [gcarq/rusty-blockparser#7]
is that possible to make an option to dump all address with unspent balances like another aged blockparser did?

**Comment by gcarq** [comment]
Sure, this can be implemented as seperate `Callback`, it should be quite similar to `csvdump`. I will look into it

**Comment by ablankenship10** [comment]
Any update on this? Would be very useful for a project I'm working on and much nicer to actually utilize all the cores on my test machine :)

**Comment by gcarq** [comment]
@fsvm88 opened a pull request (https://github.com/gcarq/rusty-blockparser/pull/12) to add this option, please take a look if this fits your needs :-) If nothing comes up I will merge it.

**Comment by agoora** [comment]
Hi,
I have a question :
How can dump all  hash160, and address with unspent balances like  "znort987/blockparser" ?
Please let me know.

**Comment by gcarq** [comment]
This has been implemented as `unspentcsvdump`.

Example: 

```
./rusty-blockparser -d /path/to/bitcoin/blocks unspentcsvdump /path/to/dump
```
