### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by mariopaolo** [gcarq/rusty-blockparser#73]
I see the last commit is from August 2020.
Does this mean the code is now stable and feature complete, or it means this project is not maintained anymore? 

thanks

**Comment by Congyuwang** [comment]
There are still quite a few numbers of TODOs in the source code. The implementation of script interpreter is apparently still not complete.

**Comment by Congyuwang** [comment]
I somehow decided to finish some of the TODOs of the project by myself (ie. mainly to support classifying Multisig script.)

Pure rust version: https://github.com/Congyuwang/BitcoinQueryRust
A corresponding python package using PyO3: https://github.com/Congyuwang/BitcoinQueryPy

- Uses rust/bitcoin library.
- Add support for txindex levelDB, allowing looking up transactions by `txid`.
- Add support for MUlTISIG script identification and address extraction.

**Comment by gcarq** [comment]
It is no longer actively maintained, once a year I touch it again if I want to get some analytics data, however with #62 it shouldn't require much of attention since most of the moving parts are outsourced to [rust-bitcoin](https://github.com/rust-bitcoin/rust-bitcoin).

**Comment by gcarq** [comment]
Functionality of #62 has been implemented, most of major issues have been fixed but there are still a few rough edges, especially for altcoins.

**Comment by gcarq** [comment]
For bitcoin this can be considered maintained
