### ISSUE TITLE
SegWit support

### ISSUE THREAD

**Issue by dev4an3** [gcarq/rusty-blockparser#74]
Please can you tell me when the SegWit support is ready to merge. Or maybe you have some documentation how I can use the updated files. I work only with the Bitcoin blockchain on a windows system.

**Comment by gcarq** [comment]
You can use the `use-bitcoin-lib` branch for now, for example:
```
$ git clone https://github.com/gcarq/rusty-blockparser.git
$ cd rusty-blockparser/
$ git checkout use-bitcoin-lib
$ cargo build --release
$ ./target/release/rusty-blockparser
```

**Comment by dev4an3** [comment]
Thnx, It works!!
