### ISSUE TITLE
Question about csvdump

### ISSUE THREAD

**Issue by AlvinLi20** [gcarq/rusty-blockparser#85]
Hi, I'm using this block parser for a school project, and I was wondering what indexPrevOut and indexOut mean. I would like to get transaction fees for each block, and the number of unique address by day from the data within the block so I'm not sure which columns to use

**Comment by AlvinLi20** [comment]
i have figured out how to get miners revenue

**Comment by gcarq** [comment]
`hashPrevOut` and `IndexPrevOut` define the [Outpoint](https://developer.bitcoin.org/reference/transactions.html#outpoint-the-specific-part-of-a-specific-output) that is going to be used as transaction input for the current transaction. Where `hashPrevOut` holds the txid and `IndexPrevOut` the index that references the specific output to spend.
`IndexOut` is also an index that references this specific output in a transaction, which will be `IndexPrevOut` in the followup transaction when the unspent transaction is going to be spent.

As you probably already figured out, the first transaction in a block is the [coinbase](https://developer.bitcoin.org/reference/transactions.html#coinbase-input-the-input-of-the-first-transaction-in-a-block) transaction which has no `hashPrevOut` and `IndexPrevOut` set as they are newly minted.

Hope this helps
