### ISSUE TITLE
pubkey only in some tx_out

### ISSUE THREAD

**Issue by jrp27514** [gcarq/rusty-blockparser#92]
Rusty is great, and perhaps this is a documentation issue or just confusion on my part, but the tx_out data has SOME public keys with opcodes (which is good)  but quite many tx_out records have an address hash as the 4th token along with the actual address as the 5th token.  I don't see any value in the address hash and certainly doesn't seem relevant as any type of key signature for the tx, So where is the missing pubkey/ validation sig?

**Comment by gcarq** [comment]
I assume this is on the Bitcoin blockchain. Can you link some txids with this behavior? I will take a look

**Comment by jrp27514** [comment]
starting from Bitcoin block 0 I generated csvdump tx_out-0-132623.csv. 80% of tx's in this file like this:
token 4 starting with 76a914 followed by 20 byte hash which is the same address as token 5and provides no real value that I can see

f72e0866bf2bf6709ec864e01210646acd9e8b2cbe5b7249dc9136e4726851cb;0;100000000;76a91431f19a7d0379f56cb3be0761c21f1f0c9553a47f88ac;15Z5YJaaNSxeynvr6uW6jQZLwq3n1Hu6RX

unhashed you can see it is same address
https://blockchain.info/q/hashtoaddress/31f19a7d0379f56cb3be0761c21f1f0c9553a47f88ac

some token 4 are pubkeys starting with 4104.. but most are these 76a914's, maybe part of a signature but not pubkey

**Comment by gcarq** [comment]
The column 4 refers to the `pkscript` in the output (see the example below). This has been called `scriptPubKey` [originally](https://en.bitcoin.it/wiki/Transaction#General_format_.28inside_a_block.29_of_each_output_of_a_transaction_-_Txout) and I used the same wording, but it does contain the whole [script](https://en.bitcoin.it/wiki/Script) and not just the publickey as someone would guess. I Hope that makes sense.

For example the given transaction https://www.blockchain.com/explorer/transactions/btc/f72e0866bf2bf6709ec864e01210646acd9e8b2cbe5b7249dc9136e4726851cb
![Screenshot_20230524_134421](https://github.com/gcarq/rusty-blockparser/assets/4720529/b69af45b-3169-41ff-a36e-eab63bc1b78e)

**Comment by gcarq** [comment]
What you refer to as `76a914` are the op codes for a common [pay-to-pubkey-hash transaction](https://en.bitcoin.it/wiki/Script#Standard_Transaction_to_Bitcoin_address_.28pay-to-pubkey-hash.29)

**Comment by jrp27514** [comment]
Thanks but a bit confusing. I thought all TX had to be signed/validated in
some way using the public key of the sender. This scriptPubKey seems to add
no real value or security by pushing a hashed address on the stack. The
address is already part of the TX.

Basically I was looking for public key info and I thought it would show up
in every TX. Apparently that is not the case?

..thx for the info

**Comment by gcarq** [comment]
There are a lot of different transaction types (e.g.: P2SH, P2PKH, P2PK, P2WSH, P2WPKH, P2TR, ...).
Some contain the public key in the script (P2PK), for others only contain a hash (P2SH, P2WSH, P2PKH, ...), and some contain neither of it and are provably unspendable (OP_RETURN).

**Comment by jrp27514** [comment]
Thanks for the explanation. I still have a lot to learn
